### ISSUE TITLE
Are you interested in upstreaming this to rustdoc?

### ISSUE THREAD

**Issue by jyn514** [roogle-rs/roogle#12]
I haven't looked in detail how roogle currently works, but I would *love* for it to be the default search rustdoc uses for the standard library and docs.rs :) would you be interested in working on that if I help out with the rusrdoc-specific parts?

**Comment by hkmatsumoto** [comment]
I think that the upstreaming is feasible if not straightforward. We need to host another dedicated API server or upgrade the existing instance. Latterly, I'll go bankrupt though.

However, I and 2 `rust-dev-tools` members had privately (in hindsight, we should've done this publicly) discussed this 2 months ago, and we concluded that roogle and rustdoc will be served for different purposes; roogle for multi-crate function search, and rustdoc for single-crate general search. One thing to note is that if we were to again discuss this, perhaps we'll end up with another conclusion because 2 months ago roogle was naive in some aspects.

**Comment by hkmatsumoto** [comment]
Maybe worth opening a thread on Zulip on this?

**Comment by Kixiron** [comment]
Docs.rs has access to (more or less) all crates, it'd be interesting to try and make roogle work with something like rustdoc's json output to allow it to operate over all documentation.
This is a pretty far out idea, but still interesting to think about

**Comment by hkmatsumoto** [comment]
> it'd be interesting to try and make roogle work with something like rustdoc's json output to allow it to operate over all documentation.

Luckily enough, the index is the output of rustdoc's json backend now.

I think the most realistic approach here is that, add index and WASM of roogle to the resulting files of `cargo doc`.

**Comment by Kixiron** [comment]
Yah, that definitely sounds good to me. In fact, it's much easier and could still provide cross-crate searches with some sort of "add crate" functionality (that is, you select crates to add to your search pool) and the site sends across the extra indices to be searched. 
Best of both worlds imo, user flexibility and light on the host server

**Comment by hkmatsumoto** [comment]
I need some elaboration on the "add crate" feature. Is this something like users requests a crate to be added to the search index?
IIUC that's definitely nice.

By the way, roogle now partially achieves the cross-crate search so please check that out (cf. b0ff61b31bc9129f6301f0895984b9a52e074143).
